import type { MailThread } from '../shared/types.ts'

const demoUser = { name: 'Alex Demo', email: 'alex.demo@example.test' }

export const mockMailThreads: MailThread[] = [
  {
    id: 'thread_demo_property_001',
    subject: 'Two new saved-search matches',
    snippet: 'Property Scout found two listings matching your saved search near Lakeview District.',
    sourceLabel: 'Property Scout',
    mailbox: 'inbox',
    unread: true,
    starred: false,
    tags: ['real-estate', 'notimportant'],
    participants: [{ name: 'Property Scout', email: 'alerts@property-scout.example.test' }],
    lastMessageAt: '2026-07-23T15:19:00.000Z',
    messages: [{
      id: 'msg_demo_property_001',
      sender: { name: 'Property Scout', email: 'alerts@property-scout.example.test' },
      recipients: [demoUser],
      sentAt: '2026-07-23T15:19:00.000Z',
      bodyText: 'Two listings match your saved filters: Apartment 4.5 rooms, Lakeview District, 133 m², 2 bedrooms, 2 bathrooms. Asking price: CHF 895,000.',
      bodyHtml: '<h2>Property Scout</h2><p><strong>CHF 895,000</strong></p><p>Apartment 4.5 rooms<br/>Lakeview District</p><p>133 m² · 2 bedrooms · 2 bathrooms</p>',
      attachments: [],
    }],
  },
  {
    id: 'thread_demo_invoice_002',
    subject: 'Solar production invoice — June',
    snippet: 'Please find attached the June invoice and production details for your review.',
    sourceLabel: 'Utility Billing',
    mailbox: 'inbox',
    unread: true,
    starred: true,
    tags: ['invoices', 'important'],
    participants: [{ name: 'Utility Billing', email: 'billing@utility-demo.example.test' }],
    lastMessageAt: '2026-07-23T14:41:00.000Z',
    messages: [{
      id: 'msg_demo_invoice_002',
      sender: { name: 'Utility Billing', email: 'billing@utility-demo.example.test' },
      recipients: [demoUser],
      sentAt: '2026-07-23T14:41:00.000Z',
      bodyText: 'Please find attached the June solar production invoice and the detailed production CSV. Please review the amount before payment.',
      attachments: [
        { id: 'att_demo_invoice_pdf', filename: 'solar-production-invoice-june.pdf', mediaType: 'application/pdf', byteSize: 184_320 },
        { id: 'att_demo_detail_csv', filename: 'production-june.csv', mediaType: 'text/csv', byteSize: 12_440 },
      ],
    }],
  },
  {
    id: 'thread_demo_agent_pr_003',
    subject: 'Re: [demo-app/web] Improve onboarding flow',
    snippet: 'The review agent found two unresolved UX questions after the latest commits.',
    sourceLabel: 'Review Agent',
    mailbox: 'inbox',
    unread: false,
    starred: false,
    tags: ['agent', 'review', 'important'],
    participants: [{ name: 'Demo Engineer', email: 'engineer@example.test' }, { name: 'Review Agent', kind: 'agent' }],
    lastMessageAt: '2026-07-23T14:59:00.000Z',
    messages: [{
      id: 'msg_demo_agent_pr_003',
      sender: { name: 'Review Agent', kind: 'agent' },
      recipients: [demoUser],
      sentAt: '2026-07-23T14:59:00.000Z',
      bodyText: 'The PR is mostly ready. Two UX choices remain: whether first-run setup is mandatory, and whether the billing card should be hidden until the account has active users.',
      attachments: [{ id: 'att_demo_review_md', filename: 'review-summary.md', mediaType: 'text/markdown', byteSize: 6_108 }],
    }],
  },
  {
    id: 'thread_demo_offer_004',
    subject: 'Newsletter offer: 50€ credit this week',
    snippet: 'Discover the latest skincare news and claim a limited-time newsletter credit.',
    sourceLabel: 'Retail Newsletter',
    mailbox: 'inbox',
    unread: false,
    starred: false,
    tags: ['newsletter', 'notimportant'],
    participants: [{ name: 'Retail Newsletter', email: 'newsletter@retail-demo.example.test' }],
    lastMessageAt: '2026-07-23T11:46:00.000Z',
    messages: [{
      id: 'msg_demo_offer_004',
      sender: { name: 'Retail Newsletter', email: 'newsletter@retail-demo.example.test' },
      recipients: [demoUser],
      sentAt: '2026-07-23T11:46:00.000Z',
      bodyText: 'Discover the latest skincare news and claim a limited-time 50€ newsletter credit.',
      attachments: [],
    }],
  },
  {
    id: 'thread_demo_research_005',
    subject: 'Weekly investigation digest: offshore finance',
    snippet: 'This week’s digest summarizes a public investigation into offshore finance structures.',
    sourceLabel: 'Research Digest',
    mailbox: 'all',
    unread: false,
    starred: true,
    tags: ['newsletter', 'research'],
    participants: [{ name: 'Research Digest', email: 'digest@research-demo.example.test' }],
    lastMessageAt: '2026-07-23T07:03:00.000Z',
    messages: [{
      id: 'msg_demo_research_005',
      sender: { name: 'Research Digest', email: 'digest@research-demo.example.test' },
      recipients: [demoUser],
      sentAt: '2026-07-23T07:03:00.000Z',
      bodyText: 'This week’s digest summarizes a public investigation into offshore finance structures and links to source documents.',
      attachments: [],
    }],
  },
  {
    id: 'thread_demo_sent_006',
    subject: 'Follow-up on Lakeview apartment documents',
    snippet: 'Thanks for the documents. I will come back with a complete proposal tomorrow.',
    sourceLabel: 'Alex Demo → Property Scout',
    mailbox: 'sent',
    unread: false,
    starred: false,
    tags: ['real-estate'],
    participants: [demoUser, { name: 'Property Scout', email: 'alerts@property-scout.example.test' }],
    lastMessageAt: '2026-07-22T18:02:00.000Z',
    messages: [{
      id: 'msg_demo_sent_006',
      sender: demoUser,
      recipients: [{ name: 'Property Scout', email: 'alerts@property-scout.example.test' }],
      sentAt: '2026-07-22T18:02:00.000Z',
      bodyText: 'Thanks for the documents. I will come back with a complete proposal tomorrow.',
      attachments: [],
    }],
  },
]

export function findMockMailThread(threadId: string): MailThread | undefined {
  return mockMailThreads.find((thread) => thread.id === threadId)
}
